# Site settings
title: 李江锦的个人主页
name: 李江锦 # your name
email: jj@lijiangjin.cn # your email address
description: "李江锦的个人主页，onvif，c++，linux，WIFI"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lijiangjin.github.io" # the base hostname & protocol for your site

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
